-- Central de gerenciamento do professor — evolução aditiva e sem perda de dados.
-- Compatível com o frontend estático no GitHub Pages.

alter table public.classroom_settings
  add column if not exists activity_name text not null default 'Atividade Prática de Biologia — INF1A',
  add column if not exists edits_locked boolean not null default false,
  add column if not exists activity_finalized boolean not null default false;

alter table public.recipes
  add column if not exists review_status text not null default 'draft',
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by uuid references auth.users(id) on delete set null,
  add column if not exists row_version bigint not null default 1;

do $$ begin
  alter table public.recipes add constraint recipes_review_status_check
    check (review_status in ('draft','submitted','changes_requested','approved'));
exception when duplicate_object then null; end $$;

create table if not exists public.recipe_reviews (
  id bigint generated by default as identity primary key,
  recipe_id uuid not null references public.recipes(id) on delete cascade,
  author_id uuid references auth.users(id) on delete set null,
  event_type text not null check (event_type in ('submitted','comment','changes_requested','approved')),
  message text,
  created_at timestamptz not null default now(),
  deleted_at timestamptz,
  deleted_by uuid references auth.users(id) on delete set null,
  constraint recipe_reviews_message_length check (message is null or length(message) <= 2000)
);

create table if not exists public.group_checklist (
  group_id uuid not null references public.groups(id) on delete cascade,
  item_key text not null,
  label text not null,
  is_manual boolean not null default true,
  is_completed boolean not null default false,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  primary key (group_id, item_key),
  constraint group_checklist_key_format check (item_key ~ '^[a-z0-9_]+$'),
  constraint group_checklist_label_length check (length(btrim(label)) between 1 and 120)
);

create table if not exists public.announcements (
  id uuid primary key default gen_random_uuid(),
  title text not null default 'Aviso do professor',
  message text not null,
  is_published boolean not null default true,
  is_featured boolean not null default false,
  expires_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint announcements_title_length check (length(btrim(title)) between 1 and 120),
  constraint announcements_message_length check (length(btrim(message)) between 1 and 2000)
);

alter table public.activity_history
  add column if not exists actor_role text,
  add column if not exists target_type text,
  add column if not exists target_id text;

create index if not exists recipes_review_status_idx on public.recipes(review_status) where deleted_at is null;
create index if not exists recipes_deleted_at_idx on public.recipes(deleted_at) where deleted_at is not null;
create index if not exists recipe_reviews_recipe_created_idx on public.recipe_reviews(recipe_id, created_at desc);
create index if not exists announcements_active_idx on public.announcements(is_published, is_featured, updated_at desc) where deleted_at is null;
create index if not exists activity_history_created_idx on public.activity_history(created_at desc);
create index if not exists activity_history_action_created_idx on public.activity_history(action, created_at desc);

insert into public.group_checklist(group_id,item_key,label,is_manual)
select g.id, v.item_key, v.label, v.is_manual
from public.groups g
cross join (values
 ('members_defined','Integrantes definidos',false),
 ('call_numbers','Números de chamada corretos',false),
 ('recipe_registered','Receita cadastrada',false),
 ('ingredients_filled','Ingredientes preenchidos',false),
 ('quantities_filled','Quantidades preenchidas',true),
 ('instructions_filled','Modo de preparo preenchido',false),
 ('recipe_reviewed','Receita revisada',false),
 ('teacher_approved','Aprovado pelo professor',false),
 ('ready_for_activity','Grupo pronto para atividade',true)
) v(item_key,label,is_manual)
on conflict (group_id,item_key) do nothing;

insert into public.announcements(message,is_published,is_featured,created_by,updated_by)
select cs.announcement,true,true,cs.updated_by,cs.updated_by
from public.classroom_settings cs
where cs.id=1 and nullif(btrim(cs.announcement),'') is not null
  and not exists(select 1 from public.announcements)
on conflict do nothing;

alter table public.recipe_reviews enable row level security;
alter table public.group_checklist enable row level security;
alter table public.announcements enable row level security;

revoke all on public.recipe_reviews, public.group_checklist, public.announcements from anon, authenticated;
grant select on public.recipe_reviews, public.group_checklist to authenticated;
grant select on public.announcements to anon, authenticated;

drop policy if exists recipe_reviews_authorized_read on public.recipe_reviews;
create policy recipe_reviews_authorized_read on public.recipe_reviews for select to authenticated
using (
  deleted_at is null and exists (
    select 1 from public.profiles viewer
    join public.recipes r on r.id=recipe_reviews.recipe_id
    where viewer.id=(select auth.uid()) and not viewer.is_anonymous
      and (viewer.role='teacher' or viewer.group_id=r.group_id)
  )
);

drop policy if exists group_checklist_authorized_read on public.group_checklist;
create policy group_checklist_authorized_read on public.group_checklist for select to authenticated
using (exists(select 1 from public.profiles p where p.id=(select auth.uid()) and not p.is_anonymous and (p.role='teacher' or p.group_id=group_checklist.group_id)));

drop policy if exists announcements_public_read on public.announcements;
create policy announcements_public_read on public.announcements for select to anon, authenticated
using (deleted_at is null and is_published and (expires_at is null or expires_at > now()));

-- Receitas excluídas não são expostas pelas consultas normais.
drop policy if exists "Anyone can view recipes" on public.recipes;
drop policy if exists recipes_public_read on public.recipes;
create policy recipes_public_read on public.recipes for select to anon, authenticated using (deleted_at is null);

-- Helpers internos: nunca são endpoints públicos.
create or replace function private.current_actor_role() returns text
language sql stable security definer set search_path=''
as $$ select p.role from public.profiles p where p.id=auth.uid() and not p.is_anonymous $$;
revoke all on function private.current_actor_role() from public,anon,authenticated;

create or replace function private.require_teacher() returns void
language plpgsql stable security definer set search_path=''
as $$ begin
  if auth.uid() is null or coalesce(((auth.jwt()->>'is_anonymous')::boolean),false)
     or not exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='teacher' and not p.is_anonymous)
  then raise exception 'Apenas professores podem realizar esta ação.'; end if;
end $$;
revoke all on function private.require_teacher() from public,anon,authenticated;

create or replace function private.log_activity(
  p_action text,p_group_id uuid default null,p_target_type text default null,
  p_target_id text default null,p_metadata jsonb default '{}'::jsonb
) returns void language plpgsql security definer set search_path=''
as $$ begin
  insert into public.activity_history(group_id,actor_id,actor_role,action,target_type,target_id,details)
  values(p_group_id,auth.uid(),private.current_actor_role(),p_action,p_target_type,p_target_id,coalesce(p_metadata,'{}'::jsonb));
end $$;
revoke all on function private.log_activity(text,uuid,text,text,jsonb) from public,anon,authenticated;

create or replace function public.teacher_dashboard_snapshot()
returns jsonb language plpgsql stable security definer set search_path=''
as $$ declare result jsonb; begin
  perform private.require_teacher();
  select jsonb_build_object(
    'settings',(select to_jsonb(cs) from public.classroom_settings cs where cs.id=1),
    'metrics',jsonb_build_object(
      'students',(select count(*) from public.profiles where role='student' and not is_anonymous),
      'teachers',(select count(*) from public.profiles where role='teacher' and not is_anonymous),
      'groups',(select count(*) from public.groups),
      'recipes',(select count(*) from public.recipes where deleted_at is null),
      'students_without_group',(select count(*) from public.profiles where role='student' and not is_anonymous and group_id is null),
      'students_without_number',(select count(*) from public.profiles where role='student' and not is_anonymous and call_number is null),
      'groups_without_recipe',(select count(*) from public.groups g where not exists(select 1 from public.recipes r where r.group_id=g.id and r.deleted_at is null)),
      'review_waiting',(select count(*) from public.recipes where deleted_at is null and review_status='submitted')
    ),
    'profiles',(select coalesce(jsonb_agg(jsonb_build_object('id',p.id,'full_name',p.full_name,'role',p.role,'group_id',p.group_id,'call_number',p.call_number,'email',u.email,'created_at',p.created_at) order by p.full_name),'[]'::jsonb) from public.profiles p join auth.users u on u.id=p.id where not p.is_anonymous),
    'groups',(select coalesce(jsonb_agg(to_jsonb(g) order by g.slug),'[]'::jsonb) from public.groups g),
    'recipes',(select coalesce(jsonb_agg(to_jsonb(r) order by r.updated_at desc),'[]'::jsonb) from public.recipes r where r.deleted_at is null),
    'checklist',(select coalesce(jsonb_agg(to_jsonb(c) order by c.group_id,c.item_key),'[]'::jsonb) from public.group_checklist c),
    'announcements',(select coalesce(jsonb_agg(to_jsonb(a) order by a.updated_at desc),'[]'::jsonb) from public.announcements a where a.deleted_at is null),
    'trash',(select coalesce(jsonb_agg(to_jsonb(r) order by r.deleted_at desc),'[]'::jsonb) from public.recipes r where r.deleted_at is not null),
    'recent',(select coalesce(jsonb_agg(x order by (x->>'created_at')::timestamptz desc),'[]'::jsonb) from (select to_jsonb(h) x from public.activity_history h order by h.created_at desc limit 30) s)
  ) into result;
  return result;
end $$;
revoke all on function public.teacher_dashboard_snapshot() from public,anon;
grant execute on function public.teacher_dashboard_snapshot() to authenticated;

create or replace function public.manage_profile_extended(p_user_id uuid,p_name text,p_group_id uuid,p_call_number integer)
returns public.profiles language plpgsql security definer set search_path=''
as $$ declare result public.profiles; begin
  perform private.require_teacher();
  if nullif(btrim(p_name),'') is null or length(btrim(p_name))>120 then raise exception 'Informe um nome de até 120 caracteres.'; end if;
  if p_group_id is not null and not exists(select 1 from public.groups where id=p_group_id) then raise exception 'Grupo não encontrado.'; end if;
  if p_call_number is not null and p_call_number not between 1 and 999 then raise exception 'Número da chamada inválido.'; end if;
  update public.profiles set full_name=btrim(p_name),group_id=p_group_id,call_number=p_call_number,updated_at=now()
  where id=p_user_id and not is_anonymous returning * into result;
  if result.id is null then raise exception 'Usuário não encontrado.'; end if;
  perform private.log_activity('profile_updated',result.group_id,'profile',result.id::text,jsonb_build_object('name',result.full_name,'call_number',result.call_number));
  return result;
end $$;
revoke all on function public.manage_profile_extended(uuid,text,uuid,integer) from public,anon;
grant execute on function public.manage_profile_extended(uuid,text,uuid,integer) to authenticated;

create or replace function public.bulk_assign_students(p_user_ids uuid[],p_group_id uuid)
returns integer language plpgsql security definer set search_path=''
as $$ declare affected integer; begin
  perform private.require_teacher();
  if coalesce(array_length(p_user_ids,1),0)<1 or array_length(p_user_ids,1)>100 then raise exception 'Selecione entre 1 e 100 alunos.'; end if;
  if p_group_id is not null and not exists(select 1 from public.groups where id=p_group_id) then raise exception 'Grupo não encontrado.'; end if;
  if exists(select 1 from unnest(p_user_ids) id left join public.profiles p on p.id=id where p.id is null or p.role<>'student' or p.is_anonymous) then raise exception 'A seleção contém conta inválida.'; end if;
  update public.profiles set group_id=p_group_id,updated_at=now() where id=any(p_user_ids) and role='student' and not is_anonymous;
  get diagnostics affected=row_count;
  if affected<>array_length(p_user_ids,1) then raise exception 'A operação não pôde ser aplicada integralmente.'; end if;
  perform private.log_activity('students_bulk_moved',p_group_id,'profiles',null,jsonb_build_object('count',affected,'user_ids',p_user_ids));
  return affected;
end $$;
revoke all on function public.bulk_assign_students(uuid[],uuid) from public,anon;
grant execute on function public.bulk_assign_students(uuid[],uuid) to authenticated;

create or replace function public.set_group_details(p_group_id uuid,p_name text,p_description text)
returns public.groups language plpgsql security definer set search_path=''
as $$ declare result public.groups; begin
  perform private.require_teacher();
  if nullif(btrim(p_name),'') is null or length(btrim(p_name))>120 then raise exception 'Nome do grupo inválido.'; end if;
  if p_description is not null and length(p_description)>500 then raise exception 'Descrição muito longa.'; end if;
  update public.groups set name=btrim(p_name),description=nullif(btrim(p_description),''),updated_at=now() where id=p_group_id returning * into result;
  if result.id is null then raise exception 'Grupo não encontrado.'; end if;
  perform private.log_activity('group_updated',p_group_id,'group',p_group_id::text,jsonb_build_object('name',result.name));
  return result;
end $$;
revoke all on function public.set_group_details(uuid,text,text) from public,anon;
grant execute on function public.set_group_details(uuid,text,text) to authenticated;

create or replace function public.set_checklist_item(p_group_id uuid,p_item_key text,p_completed boolean)
returns public.group_checklist language plpgsql security definer set search_path=''
as $$ declare result public.group_checklist; begin
  perform private.require_teacher();
  update public.group_checklist set is_completed=p_completed,updated_by=auth.uid(),updated_at=now()
  where group_id=p_group_id and item_key=p_item_key and is_manual returning * into result;
  if result.group_id is null then raise exception 'Item manual não encontrado.'; end if;
  perform private.log_activity('checklist_updated',p_group_id,'checklist',p_item_key,jsonb_build_object('completed',p_completed));
  return result;
end $$;
revoke all on function public.set_checklist_item(uuid,text,boolean) from public,anon;
grant execute on function public.set_checklist_item(uuid,text,boolean) to authenticated;

create or replace function public.transition_recipe_review(p_recipe_id uuid,p_action text,p_message text default null)
returns public.recipes language plpgsql security definer set search_path=''
as $$ declare result public.recipes; actor public.profiles; settings public.classroom_settings; begin
  if auth.uid() is null or coalesce(((auth.jwt()->>'is_anonymous')::boolean),false) then raise exception 'Faça login para revisar receitas.'; end if;
  select * into actor from public.profiles where id=auth.uid() and not is_anonymous;
  select * into result from public.recipes where id=p_recipe_id and deleted_at is null for update;
  select * into settings from public.classroom_settings where id=1;
  if actor.id is null or result.id is null then raise exception 'Receita ou perfil não encontrado.'; end if;
  if p_action='submitted' then
    if actor.role<>'student' or actor.group_id is distinct from result.group_id then raise exception 'Você não pode enviar esta receita.'; end if;
    if settings.edits_locked or settings.activity_finalized or result.is_locked then raise exception 'As edições estão bloqueadas.'; end if;
    if result.review_status not in ('draft','changes_requested') then raise exception 'Esta receita não pode ser enviada agora.'; end if;
  elsif p_action in ('approved','changes_requested') then
    perform private.require_teacher();
    if result.review_status<>'submitted' then raise exception 'A receita precisa estar aguardando revisão.'; end if;
    if p_action='changes_requested' and nullif(btrim(p_message),'') is null then raise exception 'Explique a correção necessária.'; end if;
  else raise exception 'Transição inválida.'; end if;
  update public.recipes set review_status=p_action,is_locked=(p_action='approved'),row_version=row_version+1,updated_at=now(),updated_by=auth.uid() where id=p_recipe_id returning * into result;
  insert into public.recipe_reviews(recipe_id,author_id,event_type,message) values(p_recipe_id,auth.uid(),p_action,nullif(btrim(p_message),''));
  perform private.log_activity('recipe_'||p_action,result.group_id,'recipe',result.id::text,jsonb_build_object('title',result.title,'message',nullif(btrim(p_message),'')));
  return result;
end $$;
revoke all on function public.transition_recipe_review(uuid,text,text) from public,anon;
grant execute on function public.transition_recipe_review(uuid,text,text) to authenticated;

create or replace function public.add_teacher_comment(p_recipe_id uuid,p_message text)
returns public.recipe_reviews language plpgsql security definer set search_path=''
as $$ declare result public.recipe_reviews; gid uuid; begin
  perform private.require_teacher();
  if nullif(btrim(p_message),'') is null or length(btrim(p_message))>2000 then raise exception 'Comentário inválido.'; end if;
  select group_id into gid from public.recipes where id=p_recipe_id and deleted_at is null;
  if gid is null then raise exception 'Receita não encontrada.'; end if;
  insert into public.recipe_reviews(recipe_id,author_id,event_type,message) values(p_recipe_id,auth.uid(),'comment',btrim(p_message)) returning * into result;
  perform private.log_activity('teacher_comment_added',gid,'recipe',p_recipe_id::text,jsonb_build_object('review_id',result.id));
  return result;
end $$;
revoke all on function public.add_teacher_comment(uuid,text) from public,anon;
grant execute on function public.add_teacher_comment(uuid,text) to authenticated;

create or replace function public.get_recipe_reviews(p_recipe_id uuid)
returns table(id bigint,event_type text,message text,created_at timestamptz,author_name text,author_role text)
language sql stable security definer set search_path=''
as $$ select rr.id,rr.event_type,rr.message,rr.created_at,coalesce(p.full_name,'Usuário removido'),p.role
from public.recipe_reviews rr join public.recipes r on r.id=rr.recipe_id left join public.profiles p on p.id=rr.author_id
where rr.recipe_id=p_recipe_id and rr.deleted_at is null and exists(select 1 from public.profiles v where v.id=auth.uid() and not v.is_anonymous and (v.role='teacher' or v.group_id=r.group_id)) order by rr.created_at $$;
revoke all on function public.get_recipe_reviews(uuid) from public,anon;
grant execute on function public.get_recipe_reviews(uuid) to authenticated;

create or replace function public.set_classroom_control(p_action text)
returns public.classroom_settings language plpgsql security definer set search_path=''
as $$ declare result public.classroom_settings; begin
  perform private.require_teacher();
  if p_action='lock' then update public.classroom_settings set edits_locked=true where id=1 returning * into result;
  elsif p_action='unlock' then update public.classroom_settings set edits_locked=false,activity_finalized=false where id=1 returning * into result;
  elsif p_action='finalize' then update public.classroom_settings set edits_locked=true,activity_finalized=true where id=1 returning * into result; update public.recipes set is_locked=true where deleted_at is null;
  else raise exception 'Controle inválido.'; end if;
  perform private.log_activity('classroom_'||p_action,null,'classroom','1','{}'::jsonb);
  return result;
end $$;
revoke all on function public.set_classroom_control(text) from public,anon;
grant execute on function public.set_classroom_control(text) to authenticated;

create or replace function public.bulk_group_action(p_group_ids uuid[],p_action text)
returns integer language plpgsql security definer set search_path=''
as $$ declare affected integer; status_value text; begin
  perform private.require_teacher();
  if coalesce(array_length(p_group_ids,1),0)<1 or array_length(p_group_ids,1)>50 then raise exception 'Selecione entre 1 e 50 grupos.'; end if;
  if exists(select 1 from unnest(p_group_ids) id left join public.groups g on g.id=id where g.id is null) then raise exception 'A seleção contém grupo inválido.'; end if;
  if p_action like 'status:%' then
    status_value=split_part(p_action,':',2); if status_value not in ('not_started','in_progress','review','completed') then raise exception 'Status inválido.'; end if;
    update public.groups set activity_status=status_value,updated_at=now() where id=any(p_group_ids); get diagnostics affected=row_count;
    update public.recipes set is_locked=(status_value='completed'),updated_at=now() where group_id=any(p_group_ids) and deleted_at is null;
  elsif p_action in ('lock','unlock') then
    update public.recipes set is_locked=(p_action='lock'),updated_at=now() where group_id=any(p_group_ids) and deleted_at is null; get diagnostics affected=row_count;
  else raise exception 'Ação em massa inválida.'; end if;
  perform private.log_activity('groups_bulk_action',null,'groups',null,jsonb_build_object('action',p_action,'group_ids',p_group_ids,'affected',affected));
  return affected;
end $$;
revoke all on function public.bulk_group_action(uuid[],text) from public,anon;
grant execute on function public.bulk_group_action(uuid[],text) to authenticated;

create or replace function public.save_announcement(p_id uuid,p_title text,p_message text,p_published boolean,p_featured boolean,p_expires_at timestamptz)
returns public.announcements language plpgsql security definer set search_path=''
as $$ declare result public.announcements; begin
  perform private.require_teacher();
  if nullif(btrim(p_title),'') is null or length(btrim(p_title))>120 then raise exception 'Título inválido.'; end if;
  if nullif(btrim(p_message),'') is null or length(btrim(p_message))>2000 then raise exception 'Mensagem inválida.'; end if;
  if p_featured then update public.announcements set is_featured=false where deleted_at is null; end if;
  if p_id is null then insert into public.announcements(title,message,is_published,is_featured,expires_at,created_by,updated_by) values(btrim(p_title),btrim(p_message),p_published,p_featured,p_expires_at,auth.uid(),auth.uid()) returning * into result;
  else update public.announcements set title=btrim(p_title),message=btrim(p_message),is_published=p_published,is_featured=p_featured,expires_at=p_expires_at,updated_by=auth.uid(),updated_at=now() where id=p_id and deleted_at is null returning * into result; end if;
  if result.id is null then raise exception 'Aviso não encontrado.'; end if;
  update public.classroom_settings set announcement=(select message from public.announcements where deleted_at is null and is_published and (expires_at is null or expires_at>now()) order by is_featured desc,updated_at desc limit 1),announcement_updated_at=now(),updated_by=auth.uid() where id=1;
  perform private.log_activity('announcement_saved',null,'announcement',result.id::text,jsonb_build_object('published',result.is_published,'featured',result.is_featured));
  return result;
end $$;
revoke all on function public.save_announcement(uuid,text,text,boolean,boolean,timestamptz) from public,anon;
grant execute on function public.save_announcement(uuid,text,text,boolean,boolean,timestamptz) to authenticated;

create or replace function public.delete_announcement(p_id uuid)
returns void language plpgsql security definer set search_path=''
as $$ begin perform private.require_teacher(); update public.announcements set deleted_at=now(),updated_by=auth.uid(),updated_at=now(),is_published=false where id=p_id and deleted_at is null; if not found then raise exception 'Aviso não encontrado.'; end if; perform private.log_activity('announcement_deleted',null,'announcement',p_id::text,'{}'::jsonb); end $$;
revoke all on function public.delete_announcement(uuid) from public,anon;
grant execute on function public.delete_announcement(uuid) to authenticated;

create or replace function public.soft_delete_recipe(p_recipe_id uuid)
returns void language plpgsql security definer set search_path=''
as $$ declare gid uuid; begin perform private.require_teacher(); update public.recipes set deleted_at=now(),deleted_by=auth.uid(),updated_at=now() where id=p_recipe_id and deleted_at is null returning group_id into gid; if gid is null then raise exception 'Receita não encontrada.'; end if; perform private.log_activity('recipe_trashed',gid,'recipe',p_recipe_id::text,'{}'::jsonb); end $$;
revoke all on function public.soft_delete_recipe(uuid) from public,anon;
grant execute on function public.soft_delete_recipe(uuid) to authenticated;

create or replace function public.restore_recipe(p_recipe_id uuid)
returns void language plpgsql security definer set search_path=''
as $$ declare gid uuid; begin perform private.require_teacher(); update public.recipes set deleted_at=null,deleted_by=null,updated_at=now() where id=p_recipe_id and deleted_at is not null returning group_id into gid; if gid is null then raise exception 'Receita não encontrada na lixeira.'; end if; perform private.log_activity('recipe_restored',gid,'recipe',p_recipe_id::text,'{}'::jsonb); end $$;
revoke all on function public.restore_recipe(uuid) from public,anon;
grant execute on function public.restore_recipe(uuid) to authenticated;

create or replace function public.purge_recipe(p_recipe_id uuid)
returns void language plpgsql security definer set search_path=''
as $$ begin perform private.require_teacher(); delete from public.recipes where id=p_recipe_id and deleted_at is not null; if not found then raise exception 'Receita não encontrada na lixeira.'; end if; perform private.log_activity('recipe_purged',null,'recipe',p_recipe_id::text,'{}'::jsonb); end $$;
revoke all on function public.purge_recipe(uuid) from public,anon;
grant execute on function public.purge_recipe(uuid) to authenticated;

create or replace function public.get_activity_history(p_group_id uuid default null,p_action text default null,p_offset integer default 0,p_limit integer default 25)
returns table(id bigint,group_id uuid,actor_id uuid,actor_name text,actor_role text,action text,target_type text,target_id text,details jsonb,created_at timestamptz)
language sql stable security definer set search_path=''
as $$ select h.id,h.group_id,h.actor_id,coalesce(p.full_name,'Sistema'),h.actor_role,h.action,h.target_type,h.target_id,h.details,h.created_at from public.activity_history h left join public.profiles p on p.id=h.actor_id where exists(select 1 from public.profiles t where t.id=auth.uid() and t.role='teacher' and not t.is_anonymous) and (p_group_id is null or h.group_id=p_group_id) and (p_action is null or h.action=p_action) order by h.created_at desc offset greatest(p_offset,0) limit least(greatest(p_limit,1),100) $$;
revoke all on function public.get_activity_history(uuid,text,integer,integer) from public,anon;
grant execute on function public.get_activity_history(uuid,text,integer,integer) to authenticated;

create or replace function public.get_public_classroom_state()
returns jsonb language sql stable security definer set search_path=''
as $$ select jsonb_build_object(
 'settings',(select jsonb_build_object('activity_name',activity_name,'activity_finalized',activity_finalized) from public.classroom_settings where id=1),
 'announcement',(select jsonb_build_object('title',title,'message',message,'updated_at',updated_at) from public.announcements where deleted_at is null and is_published and (expires_at is null or expires_at>now()) order by is_featured desc,updated_at desc limit 1),
 'groups',(select coalesce(jsonb_agg(jsonb_build_object('id',g.id,'name',g.name,'description',g.description,'status',g.activity_status,'members',(select count(*) from public.profiles p where p.group_id=g.id and p.role='student' and not p.is_anonymous),'recipes',(select count(*) from public.recipes r where r.group_id=g.id and r.deleted_at is null),'check_done',(select count(*) from public.group_checklist c where c.group_id=g.id and (case when c.is_manual then c.is_completed else case c.item_key when 'members_defined' then exists(select 1 from public.profiles p where p.group_id=g.id and p.role='student' and not p.is_anonymous) when 'call_numbers' then not exists(select 1 from public.profiles p where p.group_id=g.id and p.role='student' and not p.is_anonymous and p.call_number is null) and exists(select 1 from public.profiles p where p.group_id=g.id and p.role='student' and not p.is_anonymous) when 'recipe_registered' then exists(select 1 from public.recipes r where r.group_id=g.id and r.deleted_at is null) when 'ingredients_filled' then exists(select 1 from public.recipes r where r.group_id=g.id and r.deleted_at is null and length(btrim(r.ingredients))>0) when 'instructions_filled' then exists(select 1 from public.recipes r where r.group_id=g.id and r.deleted_at is null and length(btrim(r.instructions))>0) when 'recipe_reviewed' then exists(select 1 from public.recipes r where r.group_id=g.id and r.deleted_at is null and r.review_status in ('changes_requested','approved')) when 'teacher_approved' then exists(select 1 from public.recipes r where r.group_id=g.id and r.deleted_at is null and r.review_status='approved') else false end end)),'check_total',(select count(*) from public.group_checklist c where c.group_id=g.id)) order by g.slug),'[]'::jsonb) from public.groups g)
) $$;
revoke all on function public.get_public_classroom_state() from public;
grant execute on function public.get_public_classroom_state() to anon,authenticated;

-- Bloqueio global também é imposto nas escritas do aluno.
create or replace function public.guard_recipe_classroom() returns trigger
language plpgsql security definer set search_path=''
as $$ declare user_role text; group_status text; global_lock boolean; finalized boolean; begin
  select role into user_role from public.profiles where id=auth.uid() and not is_anonymous;
  select activity_status into group_status from public.groups where id=coalesce(new.group_id,old.group_id);
  select edits_locked,activity_finalized into global_lock,finalized from public.classroom_settings where id=1;
  if user_role is distinct from 'teacher' and (global_lock or finalized or group_status='completed') then raise exception 'As edições desta atividade estão bloqueadas.'; end if;
  if tg_op='UPDATE' and user_role is distinct from 'teacher' and (old.is_locked or old.review_status in ('submitted','approved')) then raise exception 'Esta receita não está liberada para edição.'; end if;
  if tg_op='DELETE' and user_role is distinct from 'teacher' then raise exception 'Apenas o professor pode excluir receitas.'; end if;
  if tg_op in ('INSERT','UPDATE') then new.row_version=coalesce(old.row_version,0)+1; end if;
  return coalesce(new,old);
end $$;
revoke all on function public.guard_recipe_classroom() from public,anon,authenticated;

-- Restringe privilégios de tabela ao mínimo necessário; RLS continua como segunda barreira.
revoke all on public.activity_history from anon,authenticated;
grant select on public.activity_history to authenticated;
revoke insert,update,delete,truncate,references,trigger on public.groups,public.profiles,public.classroom_settings from anon;
revoke insert,update,delete,truncate,references,trigger on public.activity_history from anon,authenticated;
revoke delete on public.recipes from anon,authenticated;

do $$ begin
  alter publication supabase_realtime add table public.recipe_reviews;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.announcements;
exception when duplicate_object then null; end $$;
